version: 2
jobs:
    build:
        working_directory: ~/matlab2cpp
        docker:
            - image: circleci/python:2.7.14
        steps:
            - checkout
            - restore_cache:
                key: reqs-{{ checksum "requirements.txt" }}
            - run:
                name: "Install Python requirements"
                command: |
                    virtualenv venv
                    . venv/bin/activate
                    pip install -Ur requirements.txt
                    pip install -e .
            - save_cache:
                key: reqs-{{ checksum "requirements.txt" }}
                paths:
                    - venv
            - run:
                name: "Run tests"
                command: |
                    . venv/bin/activate
                    python setup.py test

